proj2/baza/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='baza_index'),
]

proj2/proj2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('proj2_app.urls')),

]

proj2/proj2_app/urls.py
from django.urls import path
from . import views

app_name = 'proj2_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('hello/',views.hello, name='hello'),
    path('poruke/',views.poruke, name='poruke'),
    path('delete/<int:id>/',views.delete, name='delete'),
]

proj2/proj2_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Poruka(models.Model):
    content = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

proj2/proj2_app/forms.py
from django.forms import ModelForm
from .models import Poruka


class PorukaForm(ModelForm):
    class Meta:
        model = Poruka
        fields = ['content']

proj2/proj2_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Poruka
from .forms import PorukaForm

# Create your views here.

def index(req):
    if not req.user.is_authenticated:
        return render(req, 'index.html')
    else:
        return redirect('proj2_app:hello')

@login_required
def hello(req):
    #return render(req, 'hello.html')
    return redirect('proj2_app:poruke')

@login_required
def poruke(req):
    tmp = Poruka.objects.all()
    if req.method == 'POST':
        form = PorukaForm(req.POST)

        if form.is_valid():
            a = Poruka(content=form.cleaned_data['content'], owner=req.user)
            a.save()
            tmp = Poruka.objects.all()
            form = PorukaForm()
            return render(req, 'hello.html', {'poruke': tmp,'form':form})
        else:
            return render(req, 'hello.html', {'poruke': tmp,'form':form})
    else:
        form = PorukaForm()
        return render(req, 'hello.html', {'poruke': tmp,'form': form})

@login_required
def delete(req, id):
    if not req.user.is_superuser and not isinstance(id,int):
        redirect('proj2_app:poruke')
    else:
        p = Poruka.objects.get(id=id)
        p.delete()
        return redirect('proj2_app:poruke')

proj2/proj2_app/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <a class="navbar-brand" href="{% url 'proj2_app:index' %}">
      <img src="{% static 'django.png' %}" width="30" height="30" class="d-inline-block align-top" alt="logo"/>
      Projekat II
  </a>

    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
    {% endif %}

    {% if user.is_superuser %}
        <a class="nav-link" href="{% url 'admin:index' %}">Admin Panel</a>
    {% endif %}

</nav>

proj2/proj2_app/templates/hello.html
{%  extends 'master.html' %}
{%  block content %}
    <form method="post" action="{% url 'proj2_app:poruke' %}">
      {% csrf_token %}
      <div class="form-group">
          <input type="text" class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}">
          {% if form.content.errors %}
              <div class="alert alert-danger">
                  <ul style="text-align: left">
                      {% for error in form.content.errors %}
                          <li>{{ error }}</li>
                      {% endfor %}
                  </ul>
              </div>
          {% endif %}
      </div>
      <input type="submit" class="btn btn-primary mb-2" value="Post"/>
    </form>
    <div class="list-group">
        {% for poruka in poruke %}
          {% if user.is_superuser %}
            <a class="list-group-item list-group-item-action" href="{% url 'proj2_app:delete' poruka.id %}">
              {{poruka.created_at}} {{ poruka.owner.username }}: {{ poruka.content }}
            </a>
          {% else %}
            <li class="list-group-item">{{poruka.created_at}} {{ poruka.owner.username }}: {{ poruka.content }}</li>
          {% endif %}

        {% endfor %}
    </div>
{% endblock %}

proj2/proj2_app/templates/index.html
{%  extends 'master.html' %}

  {%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
  {% endblock %}

proj2/proj2_app/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        {% include 'header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>

proj2/proj2_app/templates/new.html
{%  extends 'master.html' %}
{%  block content %}
<form method="post" action="{% url 'proj2_app:new' %}">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}">
        {% if form.content.errors %}
            <div class="alert alert-danger">
                <ul style="text-align: left">
                    {% for error in form.content.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
    <input type="submit" class="btn btn-primary mb-2" value="Post"/>
</form>
{% endblock %}